# Generated by Django 5.0 on 2024-01-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_account_created_at_alter_account_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='work',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
