# Generated by Django 5.0 on 2024-01-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0005_alter_account_location_alter_account_work"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "user is male"),
                    ("FEMALE", "user is female"),
                    ("NONE", "user is female"),
                ],
                default="NONE",
                max_length=20,
                null=True,
            ),
        ),
    ]
