# Generated by Django 5.0 on 2024-03-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='binary_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='binary_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
